{% set version = "2.0.0" %}
# Even numbers only please to allow the noarch package automatically occupy odd numbers
{% set build_number = "2" %}

package:
  name: importlib-metadata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-{{ version }}.tar.gz
  sha256: 77a540690e24b0305878c37ffd421785a6f7e53c8b5720d211b211de8d0e95da

build:
  noarch: python
{% if build_script == 'noop' %}
  number: {{ build_number | int * 2 + 1 }}
{% else %}
  number: {{ build_number | int * 2 }}
{% endif %}

outputs:
  - name: importlib-metadata
    script: build_base.sh
    build:
      noarch: python
{% if build_script == 'noop' %}
      script: python --version
{% else %}
      script: python -m pip install --no-deps --ignore-installed .
{% endif %}
    requirements:
      host:
{% if build_script == 'noop' %}
        - python >=3.8
{% else %}
        - python >=3,<3.8
        - pip
        - setuptools_scm
{% endif %}
      run:
{% if build_script == 'noop' %}
        - python >=3.8
{% else %}
        - python >=3,<3.8
        - zipp >=0.5
{% endif %}
    test:
{% if build_script != 'noop' %}
      requires:
        - pip
      commands:
        - pip check
{% endif %}
      imports:
        - importlib_metadata

  - name: importlib_metadata
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('importlib-metadata', max_pin="x.x.x") }}
    test:
      imports:
        - importlib_metadata

about:
  home: https://gitlab.com/python-devs/importlib_metadata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
    - marcelotrevisani
